# Informações do projeto
site_name: Milk's Rota - Aplicativo Coletor
site_description: Manual de Operação do apliativo
site_author: Juscelino Santos
site_url: http://www.milksrota.com.br/
extra_css: [extra.css]


# Copyright
copyright: Copyright (c) 2018 Milk's Rota

# Documentação de tema
theme_dir: material

# Opções
extra:
  version: Versão 1.0.1
  logo: images/logo-300x82.png
  i18n:
    prev: 'Voltar'
    next: 'Proximo'
  palette:
    primary: 'blue-grey'
  author:
    github: juspoliveira

# Extensões
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - fontawesome_markdown
  - toc:
      permalink: '#'

# Árvore de páginas
pages:
  - Manual: 'index.md'
  - Abrindo Viagem: 'viagem.md'
  - Registrando Coleta: 'coleta.md'
  - Ocorrências e Fotos: 'ocorrencias.md'
  - Corrigir Coleta: 'editarColeta.md'
  - Cancelar Coleta: 'cancelarVisita.md'
  - Tanque comunitário: 'tanqueColetivo.md'
  - leite já coletado (Monitorar Tanques): 'monitorarTanques.md'
  - Fechar Viagem: 'fecharViagem.md'
  - Imprimir mapa viagem: 'mapaViagem.md'
  - Encerrar trabalho: 'sincronizarViagem.md'

